
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from './contexts/AuthContext';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "servixpress",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={inter.className} style={{width:'100%', backgroundColor:'#ff9b05'}}>
      <AuthProvider>
        {children}
      </AuthProvider>
      </body>
    </html>
  );
}
