import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./header/Header";
import AdminSidebar from "./sidebar/AdminSidebar";
import styles from '../sass/layout/admin/admin.module.scss'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>, {serviceOwnerId}: {serviceOwnerId: string}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{width:'100%', backgroundColor:'#ff9b05'}}>
        <div className={styles.layout_container}>
          <div className={styles.default}>
          <header className={styles.header}>
            <Header serviceOwnerId={serviceOwnerId}/>
          </header>
          <div className={styles.content}>
            <aside className={styles.sidebar}>
              <AdminSidebar />
            </aside>
            <main className={styles.main_content}>
              {children}
            </main>
          </div>
          </div>
        </div>
      </body>
    </html>
  );
}
