import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../_layoutcomponents/header/Header";
import Sidebar from "../_layoutcomponents/sidebar/Sidebar";
import styles from "../sass/layout/layout.module.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface DefaultLayoutProps {
  children: React.ReactNode;
  serviceOwnerId: string; // Add serviceOwnerId as part of the props
}

export default function DefaultLayout({ children, serviceOwnerId }: DefaultLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.layout_container}>
          <div className={styles.default}>
            <header className={styles.header}>
              <Header serviceOwnerId={serviceOwnerId} />
            </header>
            <div className={styles.content}>
              <aside className={styles.sidebar}>
                <Sidebar />
              </aside>
              <main className={styles.main_content}>{children}</main>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
